import './style.css';
import { createIcons, Play, Pause, SkipBack, Orbit, Move, Layers, Upload, Download, Maximize, X, ChevronRight, PanelRight, RotateCcw, Radio, Box, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Camera, Activity, Info } from 'lucide';
import { TimelineStore } from './world/timeline';
import { RuLabGraph } from './world/graph';
import { createRuLabView } from './render/view';
import type { EntityState, RenderMetrics, RuLabView, ScenarioId, ViewMode, Quality } from './contracts';

const base = import.meta.env.BASE_URL;
const app = document.querySelector<HTMLDivElement>('#app')!;
const icon = (name: string) => `<i data-lucide="${name}" aria-hidden="true"></i>`;
app.innerHTML = `
<main class="workspace">
  <div class="world-surface"><img id="reference" alt="RuLab architectural concept reference" src="${base}references/robotics.jpeg"><canvas id="world" aria-label="Interactive RuLab three dimensional world" tabindex="0"></canvas><div class="vignette"></div></div>
  <header class="topbar">
    <a class="brand" href="${base}" aria-label="WorldGraph home"><span class="brand-mark">${icon('box')}</span>worldgraph<span class="brand-dot">.</span><span class="brand-divider"></span><span class="brand-lab">RuLab</span></a>
    <nav class="view-tabs" aria-label="Rendering mode"><button data-mode="cinematic" aria-pressed="true">World</button><button data-mode="splats" aria-pressed="false">Gaussian</button><button data-mode="graph" aria-pressed="false">Graph</button></nav>
    <div class="top-actions"><span class="source-pill"><span></span>Authored world</span><button class="icon-button" id="info" aria-label="About this world">${icon('info')}</button><button class="icon-button" id="panel-toggle" aria-label="Toggle world inspector" aria-expanded="true">${icon('panel-right')}</button></div>
  </header>
  <aside class="scene-rail" aria-label="RuLab configurations"><span class="eyebrow">ENVIRONMENTS</span><button class="scene-card active" data-scenario="robotics" aria-label="01 Robotics lab" aria-pressed="true"><img src="${base}references/robotics.jpeg" alt=""><span><b>01</b> Robotics lab</span></button><button class="scene-card" data-scenario="hospitality" aria-label="02 Hospitality lab" aria-pressed="false"><img src="${base}references/hospitality.jpeg" alt=""><span><b>02</b> Hospitality lab</span></button><button class="scene-card" data-scenario="healthcare" aria-label="03 Healthcare lab" aria-pressed="false"><img src="${base}references/healthcare.jpeg" alt=""><span><b>03</b> Healthcare lab</span></button><button class="rail-import" id="import-splat" aria-label="Open splat">${icon('upload')}<span>Open splat</span></button><input id="splat-file" type="file" accept=".ply,.splat,.spz" hidden></aside>
  <section class="world-caption"><div class="location-line"><span class="live-dot"></span><span id="scene-kicker">RULAB / ROBOTICS</span><span class="caption-separator">/</span><span>SPACE + TIME</span></div><h1 id="scene-title">Tomorrow,<br><em>in motion.</em></h1><p id="scene-description">Explore the lab. Follow an experiment. <br>See every moment from a new perspective.</p><div class="camera-presets" aria-label="Camera positions"><button data-shot="overview" class="active">${icon('orbit')}Overview</button><button data-shot="robot">${icon('box')}Robot</button><button data-shot="drone">${icon('move')}Flight</button><button data-shot="rf">${icon('radio')}RF bay</button></div></section>
  <aside class="inspector" id="inspector" aria-label="World inspector"><div class="inspector-heading"><div><span class="eyebrow">WORLD STATE</span><h2>A living experiment</h2></div><span class="small-dot"></span></div><p id="capture-note" hidden>Local capture preview. Scale and coordinates are unverified. Choose an environment to restore the authored experiment.</p><div class="mini-map"><svg viewBox="0 0 260 140" aria-label="Top down lab map"><defs><pattern id="grid" width="13" height="13" patternUnits="userSpaceOnUse"><path d="M 13 0 L 0 0 0 13" fill="none" stroke="#ffffff0d" stroke-width=".5"/></pattern></defs><rect width="260" height="140" fill="url(#grid)"/><path d="M30 16H230V124H30Z M30 48H64V124 M196 16V62H230" fill="#73847c15" stroke="#81948b70"/><path d="M108 30H151Q157 30 157 37V106Q157 111 151 111H108Q103 111 103 105V36Q103 30 108 30Z" fill="none" stroke="#b4c9b666" stroke-dasharray="3 4"/><g id="map-entities"></g><g id="map-camera"></g></svg><span>LOCAL FRAME · METRES</span></div><div class="inspector-stats"><div><span id="entity-count">6</span><small>objects</small></div><div><span id="splat-count">···</span><small>Gaussians</small></div><div><span id="fps">···</span><small id="fps-label">FPS</small></div></div><div class="inspector-section"><div class="section-label">OBJECTS<span>SELECT TO INSPECT</span></div><div id="object-list"></div></div><section class="entity-detail" id="entity-detail" aria-live="polite"></section><div class="graph-health"><span id="graph-dot"></span><span id="graph-status">Loading Rust / WASM</span><b id="graph-count"></b></div></aside>
  <div class="render-notice" id="render-notice" role="status"><span class="spinner"></span><b>Preparing your world</b><span>Loading geometry and Gaussian renderer</span></div>
  <div class="mobile-move" aria-label="Camera movement"><button data-move="0,-1" aria-label="Move left">${icon('arrow-left')}</button><div><button data-move="1,0" aria-label="Move forward">${icon('arrow-up')}</button><button data-move="-1,0" aria-label="Move backward">${icon('arrow-down')}</button></div><button data-move="0,1" aria-label="Move right">${icon('arrow-right')}</button></div>
  <footer class="transport"><div class="transport-main"><button id="play" class="play-button" aria-label="Play experiment">${icon('play')}</button><button id="restart" class="icon-button" aria-label="Restart timeline">${icon('skip-back')}</button><div class="timecode"><b id="time">00:00.0</b><span>/ 02:00</span></div><div class="timeline-wrap"><div class="timeline-labels"><span>EXPERIMENT 001</span><span id="playback-state">PAUSED</span></div><div class="timeline-track"><div id="event-markers"></div><input id="timeline" aria-label="Experiment time" type="range" min="0" max="120" value="0" step="0.05"></div><div class="timeline-ticks"><span>00:00</span><span>00:30</span><span>01:00</span><span>01:30</span><span>02:00</span></div></div><select id="speed" aria-label="Playback speed"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select><button class="icon-button" id="export" aria-label="Export experiment">${icon('download')}</button><button class="icon-button" id="restore" aria-label="Import experiment">${icon('upload')}</button><input id="experiment-file" type="file" accept=".json" hidden><button class="icon-button fullscreen" id="fullscreen" aria-label="Toggle fullscreen">${icon('maximize')}</button></div><div class="transport-meta"><span><span class="key">W A S D</span> move <span class="meta-divider">·</span> Drag to look <span class="meta-divider">·</span> Scroll to zoom</span><span class="render-meta" id="render-meta">THREE.JS + SPARK</span><label>Detail <select id="quality" aria-label="Rendering detail"><option value="auto">Adaptive</option><option value="performance">Performance</option><option value="quality">Quality</option></select></label></div></footer>
  <div id="toast" class="toast" role="status" hidden></div>
  <dialog id="about"><div class="dialog-title"><span class="eyebrow">WORLDGRAPH / RULAB</span><button id="close-about" class="icon-button" aria-label="Close information">${icon('x')}</button></div><h2>A world you can<br><em>revisit.</em></h2><p>Move through a spatial RuLab scene and replay a 120 second experiment. Objects keep their identities as you change your viewpoint or rewind time.</p><dl><dt>Appearance</dt><dd>Authored architecture rendered with Gaussian primitives and conventional materials. Reference images illustrate the intended facility.</dd><dt>Motion</dt><dd>Deterministic robot, vehicle and drone animation. This demonstration does not run a learned world model or physical robot controller.</dd><dt>WorldGraph</dt><dd>The actual Rust graph runs locally through WebAssembly. Your scene and experiment imports stay on your device.</dd><dt>Bring your own capture</dt><dd>Open a Gaussian PLY, SPLAT or SPZ file up to 64 MiB and 500,000 Gaussians. Choose an environment to restore the authored scene.</dd></dl><a href="https://github.com/ruvnet/worldgraph" target="_blank" rel="noopener noreferrer">Explore the source ${icon('chevron-right')}</a><button id="export-graph" class="secondary-button">Export WorldGraph snapshot ${icon('download')}</button><button id="export-metrics" class="secondary-button">Export rendering evidence ${icon('activity')}</button><div id="evidence-summary"></div></dialog>
</main>`;
const icons = { Play, Pause, SkipBack, Orbit, Move, Layers, Upload, Download, Maximize, X, ChevronRight, PanelRight, RotateCcw, Radio, Box, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Camera, Activity, Info };
const refreshIcons = () => createIcons({ icons, attrs: { 'stroke-width': 1.5 } });
refreshIcons();
const $ = <T extends HTMLElement = HTMLElement>(id: string) => document.getElementById(id) as T;
let timeline = new TimelineStore('robotics');
let view: RuLabView | undefined;
const graph = new RuLabGraph();
let playing = false, speed = 1, selected = 'robot-1', last = performance.now(), lastSync = -1;
let metrics: RenderMetrics | undefined;
let detailSignature = '';
let lastScenario: ScenarioId = 'robotics';
const samples: number[] = [];
let toastTimer: ReturnType<typeof setTimeout>;
function notify(message: string) { $('toast').textContent = message; $('toast').hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').hidden = true, 5000); }
function download(name: string, data: string) { const url = URL.createObjectURL(new Blob([data], { type: 'application/json' })); const a = document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(() => URL.revokeObjectURL(url),1000); }
function formatTime(t: number) { return `${Math.floor(t/60).toString().padStart(2,'0')}:${(t%60).toFixed(1).padStart(4,'0')}`; }
function setPlaying(value: boolean) { playing=value; $('play').innerHTML=icon(playing?'pause':'play'); $('play').setAttribute('aria-label',playing?'Pause experiment':'Play experiment'); $('playback-state').textContent=playing?'PLAYING':'PAUSED'; refreshIcons(); }
function setCapturePreview(value:boolean){document.querySelector('.workspace')!.classList.toggle('capture-preview',value);document.querySelector('.source-pill')!.textContent=value?'Local capture preview':'Authored world';$('capture-note').hidden=!value;document.querySelector('.inspector h2')!.textContent=value?'Unaligned capture':'A living experiment';}
function selectEntity(id: string) { selected=id; renderUI(); }
function actionButton(text: string, fn: () => void) { const b=document.createElement('button'); b.className='entity-action'; b.textContent=text; b.onclick=()=>{try{fn();}catch(error){notify(error instanceof Error?error.message:'Action could not be recorded.');}}; return b; }
function renderUI() {
  syncScenarioUI();
  const frame=timeline.getFrame();
  $('time').textContent=formatTime(frame.time); ($<HTMLInputElement>('timeline')).value=String(frame.time);
  $('timeline').style.setProperty('--progress',`${frame.time/120*100}%`);
  $('entity-count').textContent=String(frame.entities.length);
  const detailKey = JSON.stringify([selected, frame.scenario, frame.events, frame.entities.find(e=>e.id==='rf-door')!.joints[0] > 0.5]);
  if (detailKey !== detailSignature) {
  detailSignature = detailKey;
  const list=$('object-list'); list.replaceChildren();
  for(const e of frame.entities) { const button=document.createElement('button'); button.className=`object-row ${e.id===selected?'selected':''}`; button.dataset.entity=e.id; const dot=document.createElement('span'); dot.className=`object-dot ${e.kind}`; const name=document.createElement('span'); name.textContent=e.label; const state=document.createElement('small'); state.textContent=e.kind==='sensor'?'READY':e.kind==='door'?(e.joints[0]>0.5?'OPEN':'CLOSED'):'AUTHORED'; button.append(dot,name,state); button.onclick=()=>selectEntity(e.id); list.append(button); }
  const entity=frame.entities.find(e=>e.id===selected);
  const detail=$('entity-detail'); detail.replaceChildren();
  if(entity) {
    const title=document.createElement('div'); title.className='section-label'; title.textContent=entity.label; detail.append(title);
    const coordinates=document.createElement('div'); coordinates.className='coordinates'; coordinates.textContent=entity.position.map((v,i)=>`${['E','N','U'][i]} ${v.toFixed(2)} m`).join('   '); detail.append(coordinates);
    const provenance=document.createElement('p'); provenance.textContent=`${entity.source} · ${entity.id} · ENU frame`; detail.append(provenance);
    if(entity.kind==='door') { const commands=frame.events.filter(e=>e.kind==='door'&&e.entityId===entity.id);const requestedOpen=commands.length?commands[commands.length-1].value:false;detail.append(actionButton(requestedOpen?'Close RF door':'Open RF door',()=>{timeline.record({kind:'door',entityId:entity.id,value:!requestedOpen}); lastSync=-1;renderUI();})); }
    if(['robot','amr','drone'].includes(entity.kind)) { const events=frame.events.filter(e=>e.kind==='pause-agent'&&e.entityId===entity.id&&e.time<=frame.time); const paused=events.length?events[events.length-1].value:false; detail.append(actionButton(paused?'Resume this agent':'Pause this agent',()=>{timeline.record({kind:'pause-agent',entityId:entity.id,value:!paused});lastSync=-1;renderUI();})); }
  }
  }
  const activeEntity = frame.entities.find(e=>e.id===selected);
  const coords = $('entity-detail').querySelector('.coordinates');
  if (activeEntity && coords) coords.textContent = activeEntity.position.map((v,i)=>`${['E','N','U'][i]} ${v.toFixed(2)} m`).join('   ');
  const markers=$('event-markers');markers.replaceChildren(); for(const e of frame.events) { const marker=document.createElement('span');marker.style.left=`${e.time/120*100}%`;marker.title=`${e.kind} at ${formatTime(e.time)}`;markers.append(marker); }
  const svgNS='http://www.w3.org/2000/svg';const group=$('map-entities');group.replaceChildren();
  for(const e of frame.entities) { const circle=document.createElementNS(svgNS,'circle');circle.setAttribute('cx',String(130+e.position[0]*8));circle.setAttribute('cy',String(70-e.position[1]*3));circle.setAttribute('r',e.id===selected?'5':'3');circle.setAttribute('fill',e.kind==='drone'?'#e8b581':e.kind==='sensor'?'#8bbbd8':'#c7dbbe');group.append(circle); }
}
const descriptions:Record<ScenarioId,[string,string,string]>={robotics:['RULAB / ROBOTICS','Tomorrow,<br><em>in motion.</em>','Explore the lab. Follow an experiment. <br>See every moment from a new perspective.'],hospitality:['RULAB / HOSPITALITY','Spaces that<br><em>understand.</em>','Explore service robotics and modular rooms. <br>Replay an experiment on your own terms.'],healthcare:['RULAB / HEALTHCARE','Designed<br><em>around care.</em>','Explore an authored care environment. <br>Follow assistance robots through space and time.']};
document.querySelectorAll<HTMLButtonElement>('[data-scenario]').forEach(b=>b.onclick=()=>{timeline.setScenario(b.dataset.scenario as ScenarioId);setPlaying(false);selected='robot-1';lastSync=-1;view?.reset();setCapturePreview(false);renderUI();});
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{view?.setMode(b.dataset.mode as ViewMode);document.querySelectorAll<HTMLElement>('[data-mode]').forEach(c=>c.setAttribute('aria-pressed',String(c===b)));});
document.querySelectorAll<HTMLButtonElement>('[data-shot]').forEach(b=>b.onclick=()=>{view?.cameraPreset(b.dataset.shot as 'overview'|'robot'|'drone'|'rf');document.querySelectorAll<HTMLElement>('[data-shot]').forEach(c=>c.classList.toggle('active',c===b));if(b.dataset.shot==='rf')selectEntity('rf-door');else if(b.dataset.shot==='robot')selectEntity('robot-1');else if(b.dataset.shot==='drone')selectEntity('drone-1');});
$('play').onclick=()=>{if(timeline.getFrame().time>=120)timeline.seek(0);setPlaying(!playing);};
$('restart').onclick=()=>{timeline.seek(0);lastSync=-1;renderUI();};
$('timeline').oninput=()=>{setPlaying(false);timeline.seek(Number($<HTMLInputElement>('timeline').value));lastSync=-1;renderUI();};
$('speed').onchange=()=>speed=Number($<HTMLSelectElement>('speed').value);
$('quality').onchange=()=>view?.setQuality($<HTMLSelectElement>('quality').value as Quality);
$('export').onclick=()=>download('rulab-experiment.json',timeline.exportJson());
$('restore').onclick=()=>$<HTMLInputElement>('experiment-file').click();
$('experiment-file').onchange=async()=>{const f=$<HTMLInputElement>('experiment-file').files?.[0];if(!f)return;try{if(f.size>1024*1024)throw new Error('Experiment files must be under 1 MB.');const next=TimelineStore.fromJson(await f.text());timeline=next;setPlaying(false);lastSync=-1;view?.reset();setCapturePreview(false);renderUI();notify('Experiment restored. Changes remain on this device.');}catch(e){notify(e instanceof Error?e.message:'Experiment could not be restored.');}$<HTMLInputElement>('experiment-file').value='';};
$('import-splat').onclick=()=>$<HTMLInputElement>('splat-file').click();
$('splat-file').onchange=async()=>{const f=$<HTMLInputElement>('splat-file').files?.[0];if(!f)return;try{if(!view||metrics?.backend!=='webgl2')throw new Error('Opening splats requires WebGL2 on this device.');notify('Opening your Gaussian scene…');await view.loadSplat(f);setCapturePreview(true);notify('Local scene preview loaded. Its coordinates are unverified; choose an environment to restore the authored experiment.');}catch(e){notify(e instanceof Error?e.message:'Unable to open this splat.');}$<HTMLInputElement>('splat-file').value='';};
$('panel-toggle').onclick=()=>{const open=!$('inspector').classList.contains('is-open');$('inspector').classList.toggle('is-open',open);$('panel-toggle').setAttribute('aria-expanded',String(open));};
const media=matchMedia('(min-width: 1000px)');$('inspector').classList.toggle('is-open',media.matches);$('panel-toggle').setAttribute('aria-expanded',String(media.matches));
$('info').onclick=()=>$<HTMLDialogElement>('about').showModal();$('close-about').onclick=()=>$<HTMLDialogElement>('about').close();
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Fullscreen is unavailable in this browser.');}};
$('export-graph').onclick=()=>{try{download('rulab-worldgraph.json',graph.exportJson());}catch{notify('The Rust graph is not ready. Reload and check WebAssembly support.');}};
$('export-metrics').onclick=()=>{const sorted=[...samples].sort((a,b)=>a-b);const report={schema:'worldgraph.rulab.render-evidence.v1',timestamp:new Date().toISOString(),backend:metrics?.backend??'unavailable',userAgent:navigator.userAgent,viewport:[innerWidth,innerHeight],devicePixelRatio,frameSamples:samples.length,p50FrameMs:sorted.length?sorted[Math.floor(sorted.length*.5)]:null,p95FrameMs:sorted.length?sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))]:null,metrics,limitations:['Device rendering measurement only; not reconstruction accuracy or model inference.','Authored scene and deterministic kinematics.']};download('rulab-render-evidence.json',JSON.stringify(report,null,2));};
let moveTimer:ReturnType<typeof setInterval>|undefined;
const stopMove=()=>{if(moveTimer)clearInterval(moveTimer);moveTimer=undefined;};
document.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();stopMove();b.setPointerCapture(e.pointerId);const [f,r]=b.dataset.move!.split(',').map(Number);view?.move(f*.3,r*.3);moveTimer=setInterval(()=>view?.move(f*.15,r*.15),40);};b.onpointerup=stopMove;b.onpointercancel=stopMove;b.onlostpointercapture=stopMove;});
window.addEventListener('blur',()=>{setPlaying(false);stopMove();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){setPlaying(false);stopMove();}last=performance.now();});
function onMetrics(m:RenderMetrics){metrics=m;$('world').dataset.backend=m.backend;$('world').dataset.splats=String(m.splatCount);$('world').dataset.camera=JSON.stringify(m.camera);$('world').dataset.drawCalls=String(m.drawCalls);$('world').dataset.status=m.status;$('fps').textContent=m.backend==='webgl2'?String(Math.round(m.fps)):'···';$('fps-label').textContent=m.backend==='webgl2'?'FPS':'NO GPU';$('splat-count').textContent=m.splatCount>=1000?`${(m.splatCount/1000).toFixed(1)}k`:String(m.splatCount);$('render-meta').textContent=m.backend==='webgl2'?`SPARK · ${m.frameMs.toFixed(1)} MS · ${m.drawCalls} DRAWS`:'REFERENCE VIEW · WEBGL2 REQUIRED';if(m.backend==='webgl2'&&m.frameTimesMs){samples.push(...m.frameTimesMs.filter(x=>Number.isFinite(x)&&x>0));if(samples.length>3600)samples.splice(0,samples.length-3600);}if(m.backend==='webgl2'){$('render-notice').hidden=true;$('reference').classList.add('rendered');}else{$('reference').classList.remove('rendered');$('render-notice').hidden=false;$('render-notice').innerHTML='<b>3D rendering needs WebGL2</b><span>This is a reference image. Timeline and WorldGraph remain available.</span>';const reason=document.createElement('small');reason.textContent=m.status;$('render-notice').append(reason);$('render-notice').classList.add('unavailable');}$('world').dataset.frameSamples=String(samples.length);$('evidence-summary').textContent=`${samples.length} rendering samples collected on this device.`;}
renderUI();
createRuLabView({canvas:$<HTMLCanvasElement>('world'),onSelect:selectEntity,onMetrics}).then(v=>{view=v;v.setFrame(timeline.getFrame());}).catch(e=>{onMetrics({backend:'unavailable',fps:0,frameMs:0,splatCount:0,drawCalls:0,camera:[0,0,0],status:'Renderer unavailable'});notify(e instanceof Error?e.message:'WebGL2 renderer unavailable.');});
graph.initialize().then(()=>{$('graph-dot').classList.add('ready');$('graph-status').textContent='Rust graph · WebAssembly';lastSync=-1;}).catch(()=>{$('graph-status').textContent='Rust graph unavailable';$('graph-dot').classList.add('error');});
function syncScenarioUI(){const id=timeline.getFrame().scenario;if(id===lastScenario)return;lastScenario=id;const d=descriptions[id];$('scene-kicker').textContent=d[0];$('scene-title').innerHTML=d[1];$('scene-description').innerHTML=d[2];$<HTMLImageElement>('reference').src=`${base}references/${id}.jpeg`;document.querySelectorAll<HTMLElement>('[data-scenario]').forEach(c=>{const active=c.dataset.scenario===id;c.classList.toggle('active',active);c.setAttribute('aria-pressed',String(active));});}
let renderAccumulator=0, animationId=0, disposed=false;
function tick(now:number){if(disposed)return;const dt=Math.min((now-last)/1000,.1);last=now;if(playing){const t=Math.min(120,timeline.getFrame().time+dt*speed);timeline.seek(t);if(t>=120)setPlaying(false);}const frame=timeline.getFrame();syncScenarioUI();view?.setFrame(frame);renderAccumulator+=dt;if(renderAccumulator>=.15){renderUI();renderAccumulator=0;}if(Math.abs(frame.time-lastSync)>.1||lastSync<0){try{graph.sync(frame);$('graph-count').textContent=String(graph.nodeCount());$('graph-count').dataset.time=String(frame.time);lastSync=frame.time;}catch{if(graph.status==='unavailable'){$('graph-status').textContent='Rust graph update failed';$('graph-dot').classList.remove('ready');$('graph-dot').classList.add('error');}}}animationId=requestAnimationFrame(tick);}
animationId=requestAnimationFrame(tick);
window.addEventListener('pagehide',(event)=>{stopMove();setPlaying(false);if(event.persisted)return;disposed=true;cancelAnimationFrame(animationId);clearTimeout(toastTimer);view?.dispose();graph.dispose();});
window.addEventListener('pageshow',()=>{last=performance.now();});
